spring:  
  jpa:
    hibernate: 
      ddl-auto: create-drop  
  datasource:
    url: jdbc:mysql://customersdb:3306/customers  
    username: root
    password: dbpass
    initialize: true  
  cloud: 
    stream:
      bindings: 
        input:
          destination: movements
          content-type: application/json  
          group: movementsCustomersGroup
 