spring:  
  data:
    mongodb:
      host: reportdb
      port: 27017
      database: report 
  cloud: 
    stream:
      bindings: 
        input:
          destination: movements
          content-type: application/json  
          group: movementsReportGroup